runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "crud-bucket"

handlers:
- url: /
  static_files: dist/app-frontend/index.html
  upload: dist/app-frontend/index.html

- url: /
  static_dir: dist/app-frontend